spring:
  sql:
    init:
      mode: never
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create # 테스트 실행 시마다 DB 새로 생성
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect # 이 키를 사용해서 H2 Dialect 지정
        format_sql: true
        show_sql: true

application:
  security:
    jwt:
      secret-key: aEVSS1kwanBWVUVSMTVUeVVQbFdsTVFpd2x1UG9lY1I=
      access-token-expiration: 86400000
      refresh-token-expiration: 86400000
